function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t770_init(recid){var rec=$('#rec'+recid);var navElem=rec.find('.t770');var isFixed=(navElem.css('position')=='fixed');var redactorMode=navElem.hasClass('t770_redactor-mode');if(!redactorMode){t770_highlight();navElem.removeClass('t770__beforeready');if(isFixed){t770_checkAnchorLinks(recid)}
if(isFixed&&navElem.attr('data-bgopacity-two')){t770_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t770_changebgopacitymenu(recid)},200))}
if(isFixed&&navElem.attr('data-appearoffset')){navElem.removeClass('t770__beforeready');t770_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t770_appearMenu(recid)},200))}}
if(rec.find('.t770__imglogo').attr('data-img-width')){t770_setLogoPadding(recid)}
if(rec.find('.t770__mobile_burger').length){t770_createMobileMenu(recid)}
t770_setBg(recid);$(window).bind('resize',t_throttle(function(){t770_setBg(recid)},200))}
function t770_setLogoPadding(recid){if($(window).width()>980){var t770__menu=$('#rec'+recid+' .t770');var t770__logo=t770__menu.find('.t770__logowrapper');var t770__leftpart=t770__menu.find('.t770__leftwrapper');var t770__rightpart=t770__menu.find('.t770__rightwrapper');t770__leftpart.css("padding-right",t770__logo.width()/2+50);t770__rightpart.css("padding-left",t770__logo.width()/2+50)}}
function t770_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t770__list_item a[href='"+url+"']").addClass("t-active");$(".t770__list_item a[href='"+url+"/']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t770_checkAnchorLinks(recid){if($(window).width()>=960){var t770_navLinks=$("#rec"+recid+" .t770__desktoplist .t770__list_item a:not(.tooltipstered)[href*='#']");if(t770_navLinks.length>0){t770_catchScroll(t770_navLinks)}}}
function t770_catchScroll(t770_navLinks){var t770_clickedSectionId=null,t770_sections=new Array(),t770_sectionIdTonavigationLink=[],t770_interval=100,t770_lastCall,t770_timeoutId;t770_navLinks=$(t770_navLinks.get().reverse());t770_navLinks.each(function(){var t770_cursection=t770_getSectionByHref($(this));if(typeof t770_cursection.attr("id")!="undefined"){t770_sections.push(t770_cursection)}
t770_sectionIdTonavigationLink[t770_cursection.attr("id")]=$(this)});t770_updateSectionsOffsets(t770_sections);t770_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t770_updateSectionsOffsets(t770_sections)},200));$('.t770').bind('displayChanged',function(){t770_updateSectionsOffsets(t770_sections)});setInterval(function(){t770_updateSectionsOffsets(t770_sections)},5000);t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId);t770_navLinks.click(function(){var t770_clickedSection=t770_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t770_clickedSection.attr("id")!="undefined"){t770_navLinks.removeClass('t-active');$(this).addClass('t-active');t770_clickedSectionId=t770_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t770_now=new Date().getTime();if(t770_lastCall&&t770_now<(t770_lastCall+t770_interval)){clearTimeout(t770_timeoutId);t770_timeoutId=setTimeout(function(){t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)},t770_interval-(t770_now-t770_lastCall))}else{t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)}})}
function t770_updateSectionsOffsets(sections){$(sections).each(function(){var t770_curSection=$(this);t770_curSection.attr("data-offset-top",t770_curSection.offset().top)})}
function t770_getSectionByHref(curlink){var t770_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t770_curLinkValue[0]=='/'){t770_curLinkValue=t770_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t770_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t770_curLinkValue.substring(1)+"']")}}
function t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId){var t770_scrollPosition=$(window).scrollTop(),t770_valueToReturn=t770_clickedSectionId;if(t770_sections.length!=0&&t770_clickedSectionId==null&&t770_sections[t770_sections.length-1].attr("data-offset-top")>(t770_scrollPosition+300)){t770_navLinks.removeClass('t-active');return null}
$(t770_sections).each(function(e){var t770_curSection=$(this),t770_sectionTop=t770_curSection.attr("data-offset-top"),t770_id=t770_curSection.attr('id'),t770_navLink=t770_sectionIdTonavigationLink[t770_id];if(((t770_scrollPosition+300)>=t770_sectionTop)||(t770_sections[0].attr("id")==t770_id&&t770_scrollPosition>=$(document).height()-$(window).height())){if(t770_clickedSectionId==null&&!t770_navLink.hasClass('t-active')){t770_navLinks.removeClass('t-active');t770_navLink.addClass('t-active');t770_valueToReturn=null}else{if(t770_clickedSectionId!=null&&t770_id==t770_clickedSectionId){t770_valueToReturn=null}}
return!1}});return t770_valueToReturn}
function t770_setPath(){}
function t770_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t770_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t770_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t770_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t770"),burger=el.find(".t770__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t770_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t778__init(recid){t778_unifyHeights(recid);$(window).load(function(){t778_unifyHeights(recid)});$(window).bind('resize',t_throttle(function(){t778_unifyHeights(recid)},200));$(".t778").bind("displayChanged",function(){t778_unifyHeights(recid)});setTimeout(function(){t_prod__init(recid);t778_initPopup(recid);t778__updateLazyLoad(recid)},500)}
function t778__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t778__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){t_lazyload_update()},500))}}
function t778_unifyHeights(recid){var t778_el=$('#rec'+recid),t778_blocksPerRow=t778_el.find(".t778__container").attr("data-blocks-per-row"),t778_cols=t778_el.find(".t778__content"),t778_mobScroll=t778_el.find(".t778__scroll-icon-wrapper").length;if($(window).width()<=480&&t778_mobScroll==0){t778_cols.css("height","auto");return}
var t778_perRow=+t778_blocksPerRow;if($(window).width()<=960&&t778_mobScroll>0){var t778_perRow=t778_cols.length}
else{if($(window).width()<=960){var t778_perRow=2}}
for(var i=0;i<t778_cols.length;i+=t778_perRow){var t778_maxHeight=0,t778_row=t778_cols.slice(i,i+t778_perRow);t778_row.each(function(){var t778_curText=$(this).find(".t778__textwrapper"),t778_curBtns=$(this).find(".t778__btn-wrapper_absolute"),t778_itemHeight=t778_curText.outerHeight()+t778_curBtns.outerHeight();if(t778_itemHeight>t778_maxHeight){t778_maxHeight=t778_itemHeight}});t778_row.css("height",t778_maxHeight)}}
function t778_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_sldsInit(recid+' #t778__product-'+lid_prod+'')});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t778_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]')
el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t778_updateSlider(recid+' #t778__product-'+lid_prod+'');if(window.lazy=='y'){t_lazyload_update()}});if($('#record'+recid).length==0){t778_checkUrl(recid)}
t778_copyTypography(recid)}
function t778_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t778_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t778_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy=='y'){t_lazyload_update()}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t778_closePopup()}});el.find('.t-popup__close, .t778__close-text').click(function(e){t778_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t778_closePopup()}})}
function t778_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t778_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t778_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t778__title').attr('style');var descrStyle=rec.find('.t778__descr').attr('style');rec.find('.t-popup .t778__title').attr("style",t778_removeSizeStyles(titleStyle));rec.find('.t-popup .t778__descr, .t-popup .t778__text').attr("style",t778_removeSizeStyles(descrStyle))}